apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: hirex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: jonathanscottini/gateway:1.0
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_APPLICATION_NAME
              value: "gateway-service"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery:8761/eureka/"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak:8081/realms/hirex/protocol/openid-connect/certs"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: hirex
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
