apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacancy-service
  namespace: hirex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vacancy-service
  template:
    metadata:
      labels:
        app: vacancy-service
    spec:
      containers:
        - name: vacancy-service
          image: jonathanscottini/vacancy-service:1.0
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_APPLICATION_NAME
              value: "vacancy-service"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-vacancy:5432/vacancydb"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-vacancy-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-vacancy-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak:8081/realms/hirex/protocol/openid-connect/certs"
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: vacancy-service
  namespace: hirex
spec:
  selector:
    app: vacancy-service
  ports:
    - port: 8082
      targetPort: 8082
